<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$specialFromDate = $finalPriceModel->getProduct()->getSpecialFromDate();
$specialToDate = $finalPriceModel->getProduct()->getSpecialToDate();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$timezone = $objectManager->get(\Magento\Framework\Stdlib\DateTime\TimezoneInterface::class);
$today = $timezone->date()->format('d/m/Y H:i:s');

?>
<?php if ($block->hasSpecialPrice()) :?>
    <span class="special-price">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
        <?php if ($specialFromDate || $specialToDate) : ?>
            <div class="special-date">
                <span><?= __('Today: ') . $block->escapeHtml($today) ?></span> <br>
                <?php if ($specialFromDate) : ?>
                    <span><?= __('From: ') . $block->escapeHtml($block->formatDate($specialFromDate, \IntlDateFormatter::MEDIUM, true)) ?></span> <br>
                <?php endif; ?>
                <?php if ($specialToDate) : ?>
                    <span><?= __('To: ') . $block->escapeHtml($block->formatDate($specialToDate, \IntlDateFormatter::MEDIUM, true)) ?></span>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </span>
    <span class="old-price">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php else :?>
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) :?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
